config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "pages/home"
 

  get 'history', to: 'pages#history'
  get 'analytics', to: 'pages#analytics'

  post 'search', to: 'pages#search'
  get 'getHistory', to: 'pages#getHistory'
  get 'getAnalytics', to: 'pages#getAnalytics'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/search_log.rb
class SearchLog < ApplicationRecord
  belongs_to :user
  belongs_to :session
  belongs_to :search
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :set_user_cookie_and_sessioon

  def set_user_cookie_and_sessioon

    if cookies.permanent.signed[:visitor_id]
      unless request.headers['HTTP_SESSION_ID']
        session = create_new_session
        session.user = current_user
        set_current_session(session)
        # Set the session ID in the response header
        session.save
        session_id = session.uuid
        request.set_header('session_id', session_id)
        response.set_header('session_id', session_id) 
      end
      
    else
      user = create_new_user
      session = create_new_session
      # Create a new session and associate it with the user
      session.user = user
      session.save

      # Set the session ID in the response header
      session_id = session.uuid
      response.set_header('session_id', session_id)
      set_current_session(session)
      
      # Set the visitor ID in the cookie
      uuid = user.uuid
      cookies.permanent.signed[:visitor_id] = { value: uuid, httponly: true }
    end

  end

  def create_new_user
    uuid = SecureRandom.uuid
    User.create(uuid: uuid)
  end

  def create_new_session
    uuid = SecureRandom.uuid
    Session.create(uuid: uuid)
  end

  def set_current_session(session)
    @current_session = session
  end

  def current_session 
    @current_session ||= Session.find_by(uuid: request.headers['HTTP_SESSION_ID'])
  end

  def current_user
    @current_user ||= User.find_by(uuid: cookies.signed[:visitor_id])
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :set_user_cookie_and_sessioon, only: [:home, :history, :analytics]

  def home
  end

  def history
  end

  def analytics
  end

  def search
    query = params[:text].to_s.strip

    create_search_log(query.downcase)

    if query.present?
      @articles = Article.where("title ILIKE ? OR content ILIKE ?", "%#{query}%", "%#{query}%")
    else
      @articles = []
    end

    render json: @articles
  end

  def getHistory
      search_logs = SearchLog.includes(:search)
      .where(user: current_user)

      result = search_logs.map do |log|
      {
      id: log.id,
      text: log.search.text,
      searched_at: log.created_at,
      user_id: log.user_id,
      }
      end

      render json: { result: result }, status: :ok


  end

  def getAnalytics
    searches = Search.all.order(count: :desc).limit(1000)

    render json: {
      searches: searches.map do |search|  
        {
          text: search.text,
          count: search.count,
        }
      end
    }, status: :ok
  end
 private
  def create_search_log(text)
    # Check if the text is prefex of previous search
    previous_search = SearchLog.where(user: current_user, session: current_session)

    previous_search.each do |search_log|
      if search_log.search.text.start_with?(text) 
        return
      else
        if text.start_with?(search_log.search.text) 
          search_log.destroy
          # If the text is a prefix of a previous search, destroy the previous search log
        end
      end
    end


    # Check if the search text exist in database
    search = Search.find_by(text: text)
    if search.nil?
      # If not, create a new search record
      search = Search.create(text: text, count: 0)
    end

    # Create a new search log record
    search_log = SearchLog.create(user: current_user, session: current_session, search: search)
    # Increment the search count
    search.increment!(:count)

 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "My Search App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "https://unpkg.com/tabulator-tables@6.3.1/dist/css/tabulator.min.css" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/loadingio/ldloader@v1.0.0/dist/ldld.min.css" />

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/analytics.html.erb
<%= javascript_include_tag "pages/analytics", type: "module" %>
<h1>Analytics</h1>
<p>This most searched keywords by all users</p>
<div id="analytics-table"></div>
<div id="my-loader" class="ldld full"></div>

app/views/pages/history.html.erb
<%= javascript_include_tag "pages/history", type: "module" %>

<h1>Search History</h1>
<p>This is where search history will be shown.</p>
<div id="history-table"></div>
<div id="my-loader" class="ldld full"></div>

app/views/pages/home.html.erb
<%= stylesheet_link_tag "pages/home", media: "all", "data-turbo-track": "reload" %>
<%= javascript_include_tag "pages/home", type: "module" %>

<div class="search-container">
  <input type="text" id="search-input" placeholder="Search something..." />
</div>
# <div id="example-table"></div>
<div id="results"></div>
<div id="my-loader" class="ldld full"></div>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <ul>
    <li class="<%= 'active' if current_page?(root_path) %>">
      <%= link_to 'Search', root_path %>
    </li>
    <li class="<%= 'active' if current_page?(history_path) %>">
      <%= link_to 'History', history_path %>
    </li>
    <li class="<%= 'active' if current_page?(analytics_path) %>">
      <%= link_to 'Analytics', analytics_path %>
    </li>
  </ul>
</nav>